const sounds = {
  ",": "_comma.wav",
  ".": "_period.wav",
  "a": "a.wav",
  "a!": "a!.wav",
  "affirmative": "affirmative.wav",
  "affirmative!": "affirmative!.wav",
  "alert": "alert.wav",
  "alert!": "alert!.wav",
  "alien": "alien.wav",
  "alien!": "alien!.wav",
  "all": "all.wav",
  "all!": "all!.wav",
  "am": "am.wav",
  "am!": "am!.wav",
  "anything!": "anything!.wav",
  "are": "are.wav",
  "are!": "are!.wav",
  "area": "area.wav",
  "area!": "area!.wav",
  "ass": "ass.wav",
  "ass!": "ass!.wav",
  "at!": "at!.wav",
  "away!": "away!.wav",
  "backup": "backup.wav",
  "backup!": "backup!.wav",
  "bag!": "bag!.wav",
  "bastard": "bastard.wav",
  "bastard!": "bastard!.wav",
  "blow!": "blow!.wav",
  "bogies": "bogies.wav",
  "bogies!": "bogies!.wav",
  "bravo": "bravo.wav",
  "bravo!": "bravo!.wav",
  "c2a2_hg_chat1a": "c2a2_hg_chat1a.wav",
  "c2a2_hg_chat2a": "c2a2_hg_chat2a.wav",
  "c2a2_hg_chat3a": "c2a2_hg_chat3a.wav",
  "c2a2_hg_chat4a": "c2a2_hg_chat4a.wav",
  "c2a2_hg_chat5a": "c2a2_hg_chat5a.wav",
  "c2a3_ambush_fx": "c2a3_ambush_fx.wav",
  "c2a3_ambush_vox": "c2a3_ambush_vox.wav",
  "c2a3_hg_1drag": "c2a3_hg_1drag.wav",
  "c2a3_hg_2drag": "c2a3_hg_2drag.wav",
  "c2a3_hg_3drag": "c2a3_hg_3drag.wav",
  "c2a3_hg_4drag": "c2a3_hg_4drag.wav",
  "c2a3_hg_5drag": "c2a3_hg_5drag.wav",
  "c2a3_hg_laugh": "c2a3_hg_laugh.wav",
  "c2a5_hg_abandon": "c2a5_hg_abandon.wav",
  "c2a5_hg_lebuz": "c2a5_hg_lebuz.wav",
  "call!": "call!.wav",
  "casualties!": "casualties!.wav",
  "charlie": "charlie.wav",
  "charlie!": "charlie!.wav",
  "check": "check.wav",
  "check!": "check!.wav",
  "checking": "checking.wav",
  "checking!": "checking!.wav",
  "clear": "clear.wav",
  "clear!": "clear!.wav",
  "clik": "clik.wav",
  "command": "command.wav",
  "command!": "command!.wav",
  "continue": "continue.wav",
  "continue!": "continue!.wav",
  "control": "control.wav",
  "control!": "control!.wav",
  "cover!": "cover!.wav",
  "creeps": "creeps.wav",
  "creeps!": "creeps!.wav",
  "damn": "damn.wav",
  "damn!": "damn!.wav",
  "delta": "delta.wav",
  "delta!": "delta!.wav",
  "down": "down.wav",
  "down!": "down!.wav",
  "east": "east.wav",
  "east!": "east!.wav",
  "echo": "echo.wav",
  "echo!": "echo!.wav",
  "eightymeters": "eightymeters.wav",
  "eliminate": "eliminate.wav",
  "everything": "everything.wav",
  "fall!": "fall!.wav",
  "fiftymeters": "fiftymeters.wav",
  "fight": "fight.wav",
  "fight!": "fight!.wav",
  "fire": "fire.wav",
  "fire!": "fire!.wav",
  "five": "five.wav",
  "five!": "five!.wav",
  "fivemeters": "fivemeters.wav",
  "force": "force.wav",
  "force!": "force!.wav",
  "formation": "formation.wav",
  "formation!": "formation!.wav",
  "fortymeters": "fortymeters.wav",
  "four": "four.wav",
  "four!": "four!.wav",
  "foxtrot": "foxtrot.wav",
  "foxtrot!": "foxtrot!.wav",
  "freeman": "freeman.wav",
  "freeman!": "freeman!.wav",
  "get!": "get!.wav",
  "go": "go.wav",
  "go!": "go!.wav",
  "god": "god.wav",
  "god!": "god!.wav",
  "going": "going.wav",
  "going!": "going!.wav",
  "got": "got.wav",
  "got!": "got!.wav",
  "gr_alert1": "gr_alert1.wav",
  "gr_die1": "gr_die1.wav",
  "gr_die2": "gr_die2.wav",
  "gr_die3": "gr_die3.wav",
  "gr_idle1": "gr_idle1.wav",
  "gr_idle2": "gr_idle2.wav",
  "gr_idle3": "gr_idle3.wav",
  "gr_loadtalk": "gr_loadtalk.wav",
  "gr_mgun1": "gr_mgun1.wav",
  "gr_mgun2": "gr_mgun2.wav",
  "gr_mgun3": "gr_mgun3.wav",
  "gr_pain1": "gr_pain1.wav",
  "gr_pain2": "gr_pain2.wav",
  "gr_pain3": "gr_pain3.wav",
  "gr_pain4": "gr_pain4.wav",
  "gr_pain5": "gr_pain5.wav",
  "gr_reload1": "gr_reload1.wav",
  "gr_step1": "gr_step1.wav",
  "gr_step2": "gr_step2.wav",
  "gr_step3": "gr_step3.wav",
  "gr_step4": "gr_step4.wav",
  "grenade!": "grenade!.wav",
  "guard": "guard.wav",
  "guard!": "guard!.wav",
  "have": "have.wav",
  "have!": "have!.wav",
  "he!": "he!.wav",
  "heavy": "heavy.wav",
  "heavy!": "heavy!.wav",
  "hell": "hell.wav",
  "hell!": "hell!.wav",
  "here": "here.wav",
  "here!": "here!.wav",
  "hg_civvies": "hg_civvies.wav",
  "hg_sucks": "hg_sucks.wav",
  "hold": "hold.wav",
  "hold!": "hold!.wav",
  "hole": "hole.wav",
  "hole!": "hole!.wav",
  "hostiles": "hostiles.wav",
  "hostiles!": "hostiles!.wav",
  "hot": "hot.wav",
  "hot!": "hot!.wav",
  "hundredmeters": "hundredmeters.wav",
  "i": "i.wav",
  "i!": "i!.wav",
  "in": "in.wav",
  "in!": "in!.wav",
  "is": "is.wav",
  "is!": "is!.wav",
  "kick!": "kick!.wav",
  "lay!": "lay!.wav",
  "left": "left.wav",
  "left!": "left!.wav",
  "lets": "lets.wav",
  "lets!": "lets!.wav",
  "level": "level.wav",
  "level!": "level!.wav",
  "lookout": "lookout.wav",
  "lookout!": "lookout!.wav",
  "maintain": "maintain.wav",
  "maintain!": "maintain!.wav",
  "mission": "mission.wav",
  "mission!": "mission!.wav",
  "mister": "mister.wav",
  "mister!": "mister!.wav",
  "mother!": "mother!.wav",
  "move": "move.wav",
  "move!": "move!.wav",
  "movement": "movement.wav",
  "movement!": "movement!.wav",
  "moves": "moves.wav",
  "moves!": "moves!.wav",
  "my": "my.wav",
  "my!": "my!.wav",
  "need!": "need!.wav",
  "negative": "negative.wav",
  "negative!": "negative!.wav",
  "neutralize!": "neutralize!.wav",
  "neutralized!": "neutralized!.wav",
  "niner": "niner.wav",
  "niner!": "niner!.wav",
  "no": "no.wav",
  "no!": "no!.wav",
  "north": "north.wav",
  "north!": "north!.wav",
  "nothing": "nothing.wav",
  "nothing!": "nothing!.wav",
  "objective": "objective.wav",
  "objective!": "objective!.wav",
  "of": "of.wav",
  "of!": "of!.wav",
  "oh!": "oh!.wav",
  "ok": "ok.wav",
  "ok!": "ok!.wav",
  "one": "one.wav",
  "one!": "one!.wav",
  "onefiftymeters": "onefiftymeters.wav",
  "orders": "orders.wav",
  "orders!": "orders!.wav",
  "our!": "our!.wav",
  "out": "out.wav",
  "out!": "out!.wav",
  "over": "over.wav",
  "over!": "over!.wav",
  "patrol": "patrol.wav",
  "patrol!": "patrol!.wav",
  "people": "people.wav",
  "people!": "people!.wav",
  "position": "position.wav",
  "position!": "position!.wav",
  "post": "post.wav",
  "post!": "post!.wav",
  "private": "private.wav",
  "private!": "private!.wav",
  "quiet": "quiet.wav",
  "quiet!": "quiet!.wav",
  "radio": "radio.wav",
  "radio!": "radio!.wav",
  "recon": "recon.wav",
  "recon!": "recon!.wav",
  "request!": "request!.wav",
  "right": "right.wav",
  "right!": "right!.wav",
  "roger": "roger.wav",
  "roger!": "roger!.wav",
  "sector": "sector.wav",
  "sector!": "sector!.wav",
  "secure": "secure.wav",
  "secure!": "secure!.wav",
  "seventymeters": "seventymeters.wav",
  "shit": "shit.wav",
  "shit!": "shit!.wav",
  "shot": "shot.wav",
  "shot!": "shot!.wav",
  "sign": "sign.wav",
  "sign!": "sign!.wav",
  "signs": "signs.wav",
  "signs!": "signs!.wav",
  "silence": "silence.wav",
  "silence!": "silence!.wav",
  "sir": "sir.wav",
  "sir!": "sir!.wav",
  "six": "six.wav",
  "six!": "six!.wav",
  "sixtymeters": "sixtymeters.wav",
  "some": "some.wav",
  "some!": "some!.wav",
  "something": "something.wav",
  "something!": "something!.wav",
  "south": "south.wav",
  "south!": "south!.wav",
  "squad": "squad.wav",
  "squad!": "squad!.wav",
  "stay": "stay.wav",
  "stay!": "stay!.wav",
  "suppressing!": "suppressing!.wav",
  "sweep": "sweep.wav",
  "sweep!": "sweep!.wav",
  "take!": "take!.wav",
  "tango": "tango.wav",
  "tango!": "tango!.wav",
  "target": "target.wav",
  "target!": "target!.wav",
  "team": "team.wav",
  "team!": "team!.wav",
  "tenmeters": "tenmeters.wav",
  "that": "that.wav",
  "that!": "that!.wav",
  "the": "the.wav",
  "the!": "the!.wav",
  "there": "there.wav",
  "there!": "there!.wav",
  "these": "these.wav",
  "these!": "these!.wav",
  "thirtymeters": "thirtymeters.wav",
  "this": "this.wav",
  "this!": "this!.wav",
  "those": "those.wav",
  "those!": "those!.wav",
  "three": "three.wav",
  "three!": "three!.wav",
  "tight": "tight.wav",
  "tight!": "tight!.wav",
  "twentymeters": "twentymeters.wav",
  "two": "two.wav",
  "two!": "two!.wav",
  "twohundredmeters": "twohundredmeters.wav",
  "uhh": "uhh.wav",
  "under!": "under!.wav",
  "up": "up.wav",
  "up!": "up!.wav",
  "we": "we.wav",
  "we!": "we!.wav",
  "we've": "we've.wav",
  "we've!": "we've!.wav",
  "weapons": "weapons.wav",
  "weapons!": "weapons!.wav",
  "weird": "weird.wav",
  "weird!": "weird!.wav",
  "west": "west.wav",
  "west!": "west!.wav",
  "will!": "will!.wav",
  "yeah": "yeah.wav",
  "yeah!": "yeah!.wav",
  "yes": "yes.wav",
  "yes!": "yes!.wav",
  "yessir": "yessir.wav",
  "yessir!": "yessir!.wav",
  "you": "you.wav",
  "you!": "you!.wav",
  "your": "your.wav",
  "your!": "your!.wav",
  "zero": "zero.wav",
  "zero!": "zero!.wav",
  "zone": "zone.wav",
  "zone!": "zone!.wav",
  "zulu": "zulu.wav",
  "zulu!": "zulu!.wav",
};

let audioContext = null;

function getContext() {
  if (audioContext == null) {
    audioContext = new AudioContext();
  }
  // A context created before a user gesture starts suspended.
  if (audioContext.state === "suspended") {
    audioContext.resume();
  }
  return audioContext;
}

const loadedAudioBuffersByWord = new Map();

function loadAudioBufferForWord(word) {
  let promise = loadedAudioBuffersByWord.get(word);
  if (promise == null) {
    const ctx = getContext();
    promise = fetch("/hgrunt/" + sounds[word])
      .then((response) => response.arrayBuffer())
      .then((data) => ctx.decodeAudioData(data))
      .catch((err) => {
        console.error(err);
        loadedAudioBuffersByWord.delete(word);
        return null;
      });
    loadedAudioBuffersByWord.set(word, promise);
  }
  return promise;
}

function playAudioBufferAt(buffer, startTime) {
  const ctx = getContext();
  const source = ctx.createBufferSource();
  source.buffer = buffer;
  source.connect(ctx.destination);
  source.start(startTime);
}

const hgrunt = {
  words: Object.keys(sounds),
  async playWord(word) {
    const buffer = await loadAudioBufferForWord(word);
    if (buffer == null) return;
    const ctx = getContext();
    playAudioBufferAt(buffer, ctx.currentTime);
  },
  async playSentence(words) {
    const buffers = await Promise.all(
      words.map((word) => loadAudioBufferForWord(word))
    );
    const ctx = getContext();
    let nextStart = ctx.currentTime;
    // eslint-disable-next-line no-unused-vars
    for (const buf of buffers) {
      if (buf == null) continue;
      playAudioBufferAt(buf, nextStart);
      nextStart += buf.duration;
    }
  },
};

export default hgrunt;
